const BaseUrl = 'http://127.0.0.1'
export default {
    loginAuth: BaseUrl + '/login',
    k8sResources: BaseUrl + '/api/v1/k8s/resources',
    k8sTerminalWs: 'ws://localhost:81/ws',
    k8sPodLog: BaseUrl + '/api/v1/k8s/pod/log',
    k8sEventList : BaseUrl + '/api/v1/k8s/event/list',
    k8sClusterList: BaseUrl + '/api/v1/k8s/cluster/list',
    k8sNodeList: BaseUrl + '/api/v1/k8s/node/list',
    k8sNamespaceList: BaseUrl + '/api/v1/k8s/namespace/list',
    k8sNamespaceCreate: BaseUrl + '/api/v1/k8s/namespace/create',
    k8sNamespaceDelete: BaseUrl + '/api/v1/k8s/namespace/delete',
    k8sPodList: BaseUrl + '/api/v1/k8s/pod/list',
    k8sPodDetail: BaseUrl + '/api/v1/k8s/pod/detail',
    k8sPodContainer: BaseUrl + '/api/v1/k8s/pod/container',
    k8sPodUpdate: BaseUrl + '/api/v1/k8s/pod/update',
    k8sPodDelete: BaseUrl + '/api/v1/k8s/pod/delete',
    k8sDeploymentList: BaseUrl + '/api/v1/k8s/deployment/list',
    k8sDeploymentDetail: BaseUrl + '/api/v1/k8s/deployment/detail',
    k8sDeploymentUpdate: BaseUrl + '/api/v1/k8s/deployment/update',
    k8sDeploymentReplicas: BaseUrl + '/api/v1/k8s/deployment/replicas',
    k8sDeploymentRestart: BaseUrl + '/api/v1/k8s/deployment/restart',
    k8sDeploymentCreate: BaseUrl + '/api/v1/k8s/deployment/create',
    k8sDeploymentDelete: BaseUrl + '/api/v1/k8s/deployment/delete',
    k8sDaemonSetList: BaseUrl + '/api/v1/k8s/daemonset/list',
    k8sDaemonSetDetail: BaseUrl + '/api/v1/k8s/daemonset/detail',
    k8sDaemonSetUpdate: BaseUrl + '/api/v1/k8s/daemonset/update',
    k8sDaemonSetRestart: BaseUrl + '/api/v1/k8s/daemonset/restart',
    k8sDaemonSetCreate: BaseUrl + '/api/v1/k8s/daemonset/create',
    k8sDaemonSetDelete: BaseUrl + '/api/v1/k8s/daemonset/delete',
    k8sStatefulSetList: BaseUrl + '/api/v1/k8s/statefulset/list',
    k8sStatefulSetDetail: BaseUrl + '/api/v1/k8s/statefulset/detail',
    k8sStatefulSetUpdate: BaseUrl + '/api/v1/k8s/statefulset/update',
    k8sStatefulSetReplicas: BaseUrl + '/api/v1/k8s/statefulset/replicas',
    k8sStatefulSetRestart: BaseUrl + '/api/v1/k8s/statefulset/restart',
    k8sStatefulSetCreate: BaseUrl + '/api/v1/k8s/statefulset/create',
    k8sStatefulSetDelete: BaseUrl + '/api/v1/k8s/statefulset/delete',
    k8sServiceList: BaseUrl + '/api/v1/k8s/service/list',
    k8sServiceDetail: BaseUrl + '/api/v1/k8s/service/detail',
    k8sServiceUpdate: BaseUrl + '/api/v1/k8s/service/update',
    k8sServiceCreate: BaseUrl + '/api/v1/k8s/service/create',
    k8sServiceDelete: BaseUrl + '/api/v1/k8s/service/delete',
    k8sIngressList: BaseUrl + '/api/v1/k8s/ingress/list',
    k8sIngressDetail: BaseUrl + '/api/v1/k8s/ingress/detail',
    k8sIngressUpdate: BaseUrl + '/api/v1/k8s/ingress/update',
    k8sIngressCreate: BaseUrl + '/api/v1/k8s/ingress/create',
    k8sIngressDelete: BaseUrl + '/api/v1/k8s/ingress/delete',
    k8sConfigMapList: BaseUrl + '/api/v1/k8s/configmap/list',
    k8sConfigMapDetail: BaseUrl + '/api/v1/k8s/configmap/detail',
    k8sConfigMapUpdate: BaseUrl + '/api/v1/k8s/configmap/update',
    k8sConfigMapCreate: BaseUrl + '/api/v1/k8s/configmap/create',
    k8sConfigMapDelete: BaseUrl + '/api/v1/k8s/configmap/delete',
    k8sSecretList: BaseUrl + '/api/v1/k8s/secret/list',
    k8sSecretDetail: BaseUrl + '/api/v1/k8s/secret/detail',
    k8sSecretUpdate: BaseUrl + '/api/v1/k8s/secret/update',
    k8sSecretCreate: BaseUrl + '/api/v1/k8s/secret/create',
    k8sSecretDelete: BaseUrl + '/api/v1/k8s/secret/delete',
    k8sPersistentVolumeList: BaseUrl + '/api/v1/k8s/persistentvolume/list',
    k8sPersistentVolumeDetail: BaseUrl + '/api/v1/k8s/persistentvolume/detail',
    k8sPersistentVolumeUpdate: BaseUrl + '/api/v1/k8s/persistentvolume/update',
    k8sPersistentVolumeCreate: BaseUrl + '/api/v1/k8s/persistentvolume/create',
    k8sPersistentVolumeDelete: BaseUrl + '/api/v1/k8s/persistentvolume/delete',
    k8sPersistentVolumeClaimList: BaseUrl + '/api/v1/k8s/persistentvolumeclaim/list',
    k8sPersistentVolumeClaimDetail: BaseUrl + '/api/v1/k8s/persistentvolumeclaim/detail',
    k8sPersistentVolumeClaimUpdate: BaseUrl + '/api/v1/k8s/persistentvolumeclaim/update',
    k8sPersistentVolumeClaimCreate: BaseUrl + '/api/v1/k8s/persistentvolumeclaim/create',
    k8sPersistentVolumeClaimDelete: BaseUrl + '/api/v1/k8s/persistentvolumeclaim/delete',
    k8sStorageClassList: BaseUrl + '/api/v1/k8s/storageclass/list',
    k8sStorageClassDetail: BaseUrl + '/api/v1/k8s/storageclass/detail',
    cmOptions: {
        mode: 'text/yaml',
        theme: 'dracula',
        lineNumbers: true,
        smartIndent: true,
        indentUnit: 4,
        styleActiveLine: true,
        matchBrackets: true,
        readOnly: false,
        lineWrapping: true,
    },
    termOptions: {
        rendererType: 'canvas',
        rows: 40,
        cols: 100,
        convertEol: true,
        scrollback: 10,
        cursorStyle: 'underline',
        cursorBlink: true,
        theme: {
            foreground: 'white',
            background: '#060101',
            cursor: 'help',
        }
    }
}